"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions
from builtins import (
    int,
    str,
)
from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)
from google.protobuf.message import (
    Message,
)

DESCRIPTOR: FileDescriptor

@typing_extensions.final
class HelloRequest(Message):
    DESCRIPTOR: Descriptor

    NAME_FIELD_NUMBER: int
    name: str
    def __init__(
        self,
        *,
        name: str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

@typing_extensions.final
class RepeatHelloRequest(Message):
    DESCRIPTOR: Descriptor

    NAME_FIELD_NUMBER: int
    COUNT_FIELD_NUMBER: int
    name: str
    count: int
    def __init__(
        self,
        *,
        name: str = ...,
        count: int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["count", b"count", "name", b"name"]) -> None: ...

@typing_extensions.final
class HelloReply(Message):
    DESCRIPTOR: Descriptor

    MESSAGE_FIELD_NUMBER: int
    message: str
    def __init__(
        self,
        *,
        message: str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...
